[package]
name = "pluv"
version = "0.1.0"
authors = ["Ryan Faulhaber <faulhaberryan@gmail.com>"]
edition = "2018"

[dependencies]
clap = "~2.32"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_yaml = "0.8"
dirs = "1.0.4"
reqwest = "0.9.9"
forecast = "2.0.0"